### ISSUE TITLE
 Note-Taking Application

### ISSUE THREAD

**Issue by ImBoaHancock** [ImBoaHancock/FirstRepo#3]
### Description
I am working on a simple Note-Taking application and would like to enhance its functionality. Below are the details of the proposed features:

### Current Functionality
- Users can create notes using a text area.
- Notes are displayed in a list format.

### Proposed Enhancements
1. **Edit Notes**: Allow users to click on a note to edit its content.
2. **Delete Notes**: Implement functionality for users to delete existing notes.
3. **Local Storage Support**: Save notes in local storage so they persist across page refreshes.

### Steps to Reproduce
1. Clone the repository.
2. Open the HTML file in a web browser.
3. Create a note using the text area.
4. Note the absence of options for editing or deleting notes.

### Expected Behavior
- Users should be able to edit the text of existing notes.
- Users should have the option to delete notes from the list.
- Notes should persist after refreshing the page.

### Additional Notes
Any suggestions for further enhancements or improvements are welcome! Thank you for considering this feature request!

**Comment by SubediBinod** [comment]
assign me
